FILESEXTRAPATHS_prepend := "${THISDIR}/${PN}:"
SRC_URI_append_amd = " \
	    file://gpt_disklabel.cfg \
           "

do_configure_append() {
	# We archive the config as it has to be used by do_compile
	cp .config .config.configure
}

do_compile_prepend() {
	# Do cleanup for any files that might be present due to a failed/terminated
	# build in the past, we also do not want a half-written make output for
	# the same reason
	rm -f busybox.* .config.orig .config.app.suid .config.app.nosuid \
		.config.disable.apps .config.nonapps
	oe_runmake clean

	# Copy over the .config generated by do_configure to start off with
	# otherwise if the do_compile gets terminated in between the .config
	# will suffer from any incomplete configurations
	cp .config.configure .config
}
